server:
  port: 8888
  servlet:
    context-path: /quartz
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.28.236:3306/sonnx-dev?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: guest
    password: 123456
    tomcat:
      initial-size: 20
      min-idle: 20
      max-active: 50
redis-cluster:
  redis-nodes:
  - host: 47.96.28.236
    port: 7000
  - host: 47.96.28.236
    port: 7001
  - host: 47.96.28.236
    port: 7002
  max-redirects: 1000
mybatis:
  mapper-locations: classpath:mybatis/**/*.xml
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
mybatis-sql-plugin:
  enable: true
  outer-log4j-control: false
  show-connection-info: false
snowflake:
  time-format: yyyyMMddHHmmss
  start-time: 20180101000000
  data-center-id: 1
  worker-id: 12
  bit:
    data-center-id-bits: 5
    worker-id-bits: 5
    sequence-bits: 12
quartz-cluster:
  scheduler:
    instance-name: springboot-vue-quartz
    instance-id: AUTO
    skip-update-check: true
    jmx-export: true
  job-store:
    clazz: org.quartz.impl.jdbcjobstore.JobStoreTX
    driver-delegate-class: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
    data-source: myDS
    table-prefix: qrtz_
    cluster: true
    cluster-checkin-interval: 20000
    max-misfires-to-handle-at-a-time: 1
    misfire-threshold: 120000
    tx-isolation-level-serializable: true
    select-with-lock-sql: SELECT * FROM {0}LOCKS WHERE LOCK_NAME = ? FOR UPDATE
  thread-pool:
    clazz: org.quartz.simpl.SimpleThreadPool
    thread-count: 10
    thread-priority: 5
    threads-inherit-context-class-loader-of-initializing-thread: true
  data-source:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.28.236:3306/sonnx-dev?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    user: guest
    password: 123456
    max-connections: 50
  plugin:
    trigg-history-class: org.quartz.plugins.history.LoggingJobHistoryPlugin
    shutdownhook-class: org.quartz.plugins.management.ShutdownHookPlugin
    shutdownhook-clean-shutdown: true
